version: '3.8'

services:
  crypto-ai-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto-ai-agent
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - /root/.aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - CDK_DEPLOY_REGION=${AWS_REGION:-us-east-1}
      - CDK_DEPLOY_ACCOUNT=${ACCOUNT_ID}
      - NODE_ENV=development
    command: >
      bash -c "npm run build && 
               echo 'To deploy the application, run these commands:' &&
               echo '  1. cdk bootstrap aws://${CDK_DEPLOY_ACCOUNT}/${CDK_DEPLOY_REGION}' &&
               echo '  2. cdk deploy --all --require-approval never' &&
               echo 'Entering bash shell...' &&
               bash"
    tty: true
    stdin_open: true

volumes:
  node_modules: 